### ISSUE TITLE
plot.RCModel should include survey composition fits for all the simulations in the 'RCM output' tab

### ISSUE THREAD

**Issue by tcarruth** [Blue-Matter/SAMtool#13]
Self explanatory.

E.g. see report attache
[Fit1.zip](https://github.com/Blue-Matter/SAMtool/files/6381629/Fit1.zip)
d where mean fit shows fit to survey but not 'RCM output' tab

**Comment by quang-huynh** [comment]
For some reason the report in the zip file is corrupted, but the survey comps are plotted in the 'RCM output' under the respective survey, i.e., comps from Survey 1 is under sub-tab 'Survey 1' along with the index
