### ISSUE TITLE
RCM needs a named class of data input (the list format for the data) 

### ISSUE THREAD

**Issue by tcarruth** [Blue-Matter/SAMtool#15]
Users of RCM need to be able to package their multifleet data into the RCM list format of a given class (e.g. RCMdata), know it is compatible with RCM so they can upload it to apps like MERA. That way any process using RCM can accept a formatted data list of class RCMdata safe in the knowledge it will work with RCM.

**Comment by quang-huynh** [comment]
-[] Add slots for effective sample size of all comp data
-[] Rename variables TMB (e.g., s_CAA to IAA)
-[] Allow uneven length bins
