### ISSUE TITLE
default TAC for interim MP when SCA doesn't converge?

### ISSUE THREAD

**Issue by nikolaifish** [Blue-Matter/SAMtool#28]
Hi,

I'm running some MSEs with different OM and have found that interim MPs throw an error when the assessments do not converge. It results in a missing TAC, so I wonder if there is a preferred way to set an alternative or default TAC for these situations. Interestingly I haven't had any similar issues with the same OMs when running other MPs that run the same stock assessment model (e.g. SCA_Pope). So maybe these have alternative ways of setting TACs or just are somehow not having convergence issues.

I've attached a zip file with an OM and a script to demonstrate.

Consider for example the following MP:
`iMP_avg_10 <- make_interim_MP(SCA_Pope, .HCR = "HCR_MSY", MSY_frac = 1,  assessment_interval = 10, type = "mean", type_par = 3)`

It seems that when `do_Assessment@conv==FALSE` I end up with NULL values for Iref and Cref which in turn leads the TAC estimate to be numeric(0) in `Rec@TAC <- Cref * (I_y + b * s)/(Iref + b * s)`. I finally get an error in applyMP because `rec <- do.call("cbind", lapply(temp, slot, name = X))` drops the numeric(0) values (e.g. with X="TAC") and then I get 
`"Error in TACout[mp, , ] <- recList$TAC :  number of items to replace is not a multiple of replacement length"`

because there are not enough values in `recList$TAC` to fill `TACout[mp, , ]`.

Thanks again for your time!
Nikolai

[RunMSE_SCAconvIssue.zip](https://github.com/Blue-Matter/SAMtool/files/7829782/RunMSE_SCAconvIssue.zip)

**Comment by quang-huynh** [comment]
Thanks for spotting the issue. Cref and Iref are undefined if multiple assessments don't converge, so I've set them to NA in order to return TAC = NA.

Currently, the most recent catch is used as the TAC if an MP returns NA.

**Comment by nikolaifish** [comment]
That sounds like a great solution. And the use of the most recent catch for
TAC=NA also seems like a good default.

Nikolai
