### ISSUE TITLE
no default value of `s` for `make_interim_MP(type="buffer")` when `do_Assessment@conv==FALSE`

### ISSUE THREAD

**Issue by nikolaifish** [Blue-Matter/SAMtool#29]
Hi guys,

I am running the following MP in my MSE:

`iMP_buffer_5 <- make_interim_MP(.Assess = "SCA_Pope", .HCR = "HCR_MSY", MSY_frac = 1,
                                assessment_interval = 5,
                                type = "buffer", type_par = 1)`

and occasionally get the error: 
`Error in TACout[mp, , ] <- recList$TAC : 
  number of items to replace is not a multiple of replacement length`

I think what's happening this time is again due to the SCA not converging in some of my sims, which again results in a missing value for Rec@TAC. But I think what's happening now is that there is no default value for `s` in `Rec@TAC <- Cref * (I_y + b * s)/(Iref + b * s)` when the assessment is not converging.

It looks like the code that sets `s` when `type==buffer` only works when the assessment converges:

`    if (type == "buffer") {
      if (is.null(type_par)) {
        b <- 1
      }
      else {
        b <- type_par
      }
      s <- Data@Misc[[x]]$interim$s
    }
    else {
      b <- s <- 0
    }`

Maybe you would just add the default `s=0` when you set the other values of `Rec$Misc$interim` when `!do_Assessment@conv` (lines 43-44 in iMP_buffer_5.R linked below)?:

`Rec@Misc$interim <- list(Cref = NA_real_, Iref = NA_real_,
                                next_assess_yr = next_assess_yr)`

Please let me know if you want a full reproducible example.
Cheers!
Nikolai

PS iMP_buffer_5.R is linked in txt form below

[iMP_buffer_5.R.txt](https://github.com/Blue-Matter/SAMtool/files/7946144/iMP_buffer_5.R.txt)

**Comment by quang-huynh** [comment]
Thanks for spotting the issue, I've made the change as you requested along with a general NULL catch for the TAC when these situations do pop up.

**Comment by nikolaifish** [comment]
Great! Thanks again!
Good thing I have plenty of stock assessment models that don't converge. :)

Nikolai
