### ISSUE TITLE
OMs produced by RCMfit include cpars$Data but this does not include dimnames (unlike SS2Data)

### ISSUE THREAD

**Issue by tcarruth** [Blue-Matter/SAMtool#31]
setwd("C:/GitHub/GFCM")
Data_BSB<-SS2Data("./Data/Black_Seabream/SBR_ss3ref") 
dimnames(Data_BSB@AddInd)

RCM_OM<-readRDS("./OMs/Black_Seabream/OM_BSB_RCM.rda")
dimnames(RCM_OM@cpars$Data@AddInd)

**Comment by quang-huynh** [comment]
RCM will now carry over the index names in `colnames(RCMdata@Index)`
