### ISSUE TITLE
r_prior ineffective in SP.hpp

### ISSUE THREAD

**Issue by Henning-Winker** [Blue-Matter/SAMtool#33]
Hi Quang Huynh
I think there is an issue with evoking the r_prior in SP.hpp, Line 68
if(r_prior(0) > 0) prior -= dnorm_(r, r_prior(0), r_prior(1), true) - log(r); // r prior with log-Jacobian transformation, exact with fixed n

I did some basic simulation runs for an Albacore OM (one-way-downhill) and I have to set the sd to extreme high precision to get some imprecise estimates of r, which should essentially fix r.
For example, if set use_r_prior = T  and start=list(r_prior=c(0.4,0.1)) there is no effect and the r estimate can still get to < 0.000001.
Only if set start=list(r_prior=c(0.4,0.01)) I get a behavior similar to log.sd = 0.3 in spict or jabba.

I am not too familiar with the log-Jacobian but I suggest simple test runs, but I noted that prior mean appears to be converted to log scale 
x@TMB_report$prior
So, perhaps test with a conventional lognormal r prior?

Type log_r = log(r)

if(r_prior(0) > 0) prior -= dnorm_(log_r, r_prior(0), r_prior(1), true); // standard log-normal prior (not bias correct yet)

Best wishes,
Henning

**Comment by quang-huynh** [comment]
Hi @Henning-Winker 
I ran a couple examples with a tight r prior which did return the prior mean in the model:

```
x <- SP(Data = swordfish)
summary(x@SD) # r_hat = 0.55, se = 0.15

x_pr <- SP(Data = swordfish, use_r_prior = TRUE, start = list(r_prior = c(0.35, 0.0001)))
summary(x_pr@SD) # r_hat = 0.35, se = 1e-4

x_pr2 <- SP(Data = SimulatedData, use_r_prior = TRUE, start = list(r_prior = c(0.35, 0.001)))
summary(x_pr2@SD) # r_hat = 0.35, se = 1e-3
```

Are you able to get the same result? I'm using v 1.5.0 (on github only, but I have not updated the SP code in a while)

**Comment by quang-huynh** [comment]
I believe there's also an issue with the sign of the Jacobian: https://github.com/Blue-Matter/SAMtool/commit/5f0ee8fd77e8ced13e05318d90c6c2e7e05e25b4

Could you try to see if your albacore case study works better with this fix?

Basically, it's needed because the estimated rate parameter is `x = log(FMSY)` (I've found this parameterization converges more quickly) and the Jacobian allows us to place the appropriate prior on x. Here's the code that should verify the `+log(r)` addition to the prior. Also note `TMB_report$prior` reports the negative log prior. I'd like to change the internal variable for clarity, but there's some downstream reporting that will break, so I'll have to get back to it later.

```
set.seed(24)

# Sample r, FMSY, and x from rnorm
r_mu <- 0.45
r_sd <- 0.05
r_samps <- rnorm(1e5, r_mu, r_sd)
FMSY_samps <- 0.5 * r_samps
x_samps <- log(FMSY_samps)

# Calculate the density of r, FMSY, and x from dnorm and Jacobian transformation for x
r_val <- seq(0.01, 2, 0.01)
FMSY_val <- 0.5 * r_val
x_val <- log(FMSY_val)
r_dens <- dnorm(r_val, r_mu, r_sd)
x_dens <- r_dens * abs(r_val) # With Jacobian
x_dens_no_Jacobian <- r_dens

par(mfrow = c(2, 1))

# Plot to show that the Jacobian is needed to get the proper prior for x
hist(r_samps, freq = FALSE)
lines(r_val, r_dens)
hist(x_samps, freq = FALSE)
lines(x_val, x_dens)
lines(x_val, x_dens_no_Jacobian, col = "red")

# Compare negative log-prior from above and that calculated in log space
plot(x_val, -log(x_dens), typ = "l")
log_dens2 <- dnorm(r_val, r_mu, r_sd, log = TRUE) + log(r_val)
points(x_val, -log_dens2, col = "red")

plot(r_val, -log(x_dens), typ = "l")
points(r_val, -log_dens2, col = "red")
```

**Comment by quang-huynh** [comment]
Should be fixed with lognormal r prior https://github.com/Blue-Matter/SAMtool/commit/e241fd6f3fca95f6cf597e725ca65669a53d1540
