### ISSUE TITLE
Convergence information for plot(RCMfit)

### ISSUE THREAD

**Issue by tcarruth** [Blue-Matter/SAMtool#45]
When running RCM on batches of models (e.g. BC invertebrates) and not monitoring individual model convergence, it is possible for RCM will return an RCMfit object with all simulations when in fact none have converged ('all simulations did not converge, returning all simulations'). 

When drop_nonconv=F a certain fraction of simulations might also be non converged. 

It would be helpful if the RCMfit report included two things:
- The total number of simulations in the RCMfit object 
- The total number (or fraction) of converged simulations

**Comment by quang-huynh** [comment]
Updated in https://github.com/Blue-Matter/SAMtool/commit/47227971a54d8279d68731166b0316c4cf858e34
