### ISSUE TITLE
For some reason the L50 and L50_95 parameters that control maturity at length are not being passed along to the OM properly 

### ISSUE THREAD

**Issue by tcarruth** [Blue-Matter/SAMtool#50]
In this case the OM is sent to RCMfit with only L50 and L50_95 slots set (50, and 10 respectively). 

After RCM fitting, if I plot the OM:

plot(RCMfit@OM) 

the maturity at length is more like L50 = 50, L50_95 = 20 (much flatter). 

[RCMfit.zip](https://github.com/Blue-Matter/SAMtool/files/13291115/RCMfit.zip)

**Comment by quang-huynh** [comment]
RCM uses `SampleStockPars()` to grab Mat_age and only passes this array to the conditioned OM, where L50 and L95 are subsequently back-calculated (also by `SampleStockPars`) but does not recover the original values. 

The solution is to copy over the values from the original OM to cpars in the conditioned OM (I believe this is primarily for reporting purposes as the population model uses Mat_age?)

```
StockPars <- SampleStockPars(OM)
vars <- c('L50array', 'L95array', 'ageMarray', 'age95array')

RCMfit <- RCM(OM, ...)
RCMfit@OM@cpars[vars] <- StockPars[vars]

**Comment by tcarruth** [comment]
Well if the plot(fit) is misleading we should fix that. Folks are looking at that and saying the length selectivity curve is too flat when its actually steeper according to Fit@OM@cpars$SLarray.
