### ISSUE TITLE
Truncated histograms and higher resolution histograms in plot(RCMfit)

### ISSUE THREAD

**Issue by tcarruth** [Blue-Matter/SAMtool#54]
plot(RCMfit) - the first thing you generally see is the R0 histogram in 'Operating Model > Updated parameters'. In more than 50% of cases (in my experience) there is an R0 plot with a single bar (and some single R0 sample that is much higher). To be informative these need an upper percentile x axis limit and a slightly higher resolution (half bin width). Same goes for the other histograms.

**Comment by quang-huynh** [comment]
Can do something like this to remove the top 5th quantile if the samples are skewed:
![image](https://github.com/Blue-Matter/SAMtool/assets/15094006/df99b373-2d6f-4a7a-ae58-35cd5ffe2bee)

```

nsim <- 100

noutlier <- 5
Gsamps <- rnorm(nsim-noutlier)
outlier <- rep(15, noutlier)

x <- c(Gsamps, outlier)

n <- length(x)
skewness <- (sum((x - mean(x))^3)/n)/(sum((x - mean(x))^2)/n)^(3/2)

par(mfrow = c(1, 2))
hist(x, main = "All samples")
box()
if (skewness > 3) {
  
  max_x_plot <- quantile(x, 0.95)
  hist(x[x <= max_x_plot], main = "Remove skewed samples")
  box()
  
  legend("topright", 
         paste0(round(100 * mean(max_x_plot/n)), "% > ", round(max_x_plot, 2)), 
         bty = "n",
         text.col = "red")
} else if (skewness < 3) {
  hist(x[x > quantile(x, 0.05)])
}
```
