### ISSUE TITLE
RCMfit@Misc is not to be trifled with!

### ISSUE THREAD

**Issue by tcarruth** [Blue-Matter/SAMtool#56]
Typically the idea of a Misc slot is somewhere the user can put things. If I put anything in here, downstream functions such as plot(RCMfit) fail to work! For example, I put a keepsims item for filtering simulations I wanted to leave out for obvious fitting issues:

RCMfit@Misc$keepsims = 1:24 # for example
plot(RCMfit) # error

**Comment by quang-huynh** [comment]
This is the likely culprit - https://github.com/Blue-Matter/SAMtool/blob/master/R/define_S4_class_RCModel.R#L179

Ideally, a new reporting slot is the best outcome and should be easy to update the plot function for backwards compatibility
