### ISSUE TITLE
Identify non-converged simulations in RCM plots

### ISSUE THREAD

**Issue by AdrianHordyk** [Blue-Matter/SAMtool#57]
It would be useful if the individual simulations that were detected to have not converged in an RCM are identified in the plots of the RCM output - ie predictions of fishery dynamics and fits to data.

Also would be useful to identify in the plots indices that aren't included in the likelihood - ie weighted to zero

**Comment by quang-huynh** [comment]
If you can send me an example RCM object, this may be a straightforward addition
